spring:
  application:
    name: LikeLion13th-BE

  datasource:
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql # 사용할 DB 유형 지정 (MySQL)
    database-platform: org.hibernate.dialect.MySQLDialect # Hibernate에서 사용할 MySQL 방언(dialect) 지정
    show-sql: true # 실행된 SQL 쿼리를 콘솔에 출력할지 여부
    hibernate:
      ddl-auto: update # 애플리케이션 실행 시 DB 스키마의 상태 설정
    properties:
      hibernate:
        format_sql: true # 출력되는 SQL 쿼리를 보기 좋게 포맷팅
  data:
    redis:
      host: localhost
      port: 6379
  jwt:
    secret: ls4552snq2owk3en31o22k3j4oin32kQF2dwg24w3242FSsDF2G52f2eF22GR2
    token:
      access-expiration-time: 360000
      refresh-expiration-time: 86400000

  security:
    oauth2:
      client:
        registration:
          kakao:
            authorization-grant-type: authorization_code
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: http://localhost:8080/callback/kakao
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - profile_image
              - profile_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


  mail:
    host: smtp.naver.com
    port: 465 # 네이버 표준 port번호 , 구글은 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com